source "http://rubygems.org"

# gemspec
gem 'parslet'

# autowatchr mynyml-redgreen
group :development do
  %w(rspec flexmock rdoc sdoc
guard guard-rspec guard-simple_shell
rb-fsevent growl rake
qed ae ZenTest ).
    each { |gem_name|
      gem gem_name }
end