source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/ch.elexis.core.services.rcp.StockCommissioningSystemService.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.eenv.ElexisEnvironmentServiceActivator.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.eenv.OcrMyPdfService.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.holder.ElexisServerServiceHolder.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.StickerService.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.holder.StickerServiceHolder.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.internal.EnvVarsLoginContributor.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.internal.GsonProviderService.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.internal.HttpClientProviderService.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.RoleBasedAccessControlService.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.UserService.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.holder.StockCommissioningServiceHolder.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.TraceService.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.ConfigService.xml,\
               OSGI-INF/ch.elexis.core.services.rcp.es.ElexisServerService.xml
