repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: check-xml
      files: '.*xml'
    - id: check-yaml
      files: '.*yaml|.*yml'
    - id: mixed-line-ending
      files: '.*java'
      args: ['--fix=lf']
    - id: file-contents-sorter
      files: 'plugin.*properties|messages.*properties' # but not build.properties
