default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-json
      files: '.*json'
    - id: check-xml
      files: '.*xml'
    - id: check-yaml
      files: '.*yaml|.*yml'
    - id: mixed-line-ending
      files: '.*java'
      args: ['--fix=lf']
# Using file-contents-sorter for the properties managed by the RBE
# (Resource Bundle Editor) is  a bad ide as the RBE always inserts an empty
# line between to ids
#    - id: file-contents-sorter
#      files: 'plugin.*properties|messages.*properties' # but not build.properties
  - repo: local
    hooks:
    - id: enforce-eclipse-format
      # use it locally by calling
      # pre-commit run --hook-stage manual enforce-eclipse-format --show-diff-on-failure --verbose --all-files
      stages: [manual]
      name: enforce-eclipse-format
      entry: mvn -V formatter:format --fail-at-end
      language: system
      types: [java]
      pass_filenames: false
