INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('user', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('user_external', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('executive_doctor', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('doctor', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('assistant', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('patient', '1');

INSERT INTO RIGHT_ (ID, NAME, PARENTID) VALUES ('root', 'root', '');

CREATE OR REPLACE VIEW RIGHTS_PER_ROLE AS SELECT 
	r.ID AS ROLE_ID, ri.ID AS RIGHT_ID
FROM 
	ROLE r
	LEFT JOIN ROLE_RIGHT_JOINT rrj
		ON r.ID = rrj.ROLE_ID
	LEFT JOIN RIGHT_ ri
		ON rrj.ID = ri.ID
ORDER BY r.ID;

CREATE OR REPLACE VIEW RIGHTS_PER_USER AS SELECT 
	u.ID AS USER_ID, ri.ID AS RIGHT_ID, ri.NAME AS RIGHT_NAME
FROM 
	USER_ u
	LEFT JOIN USER_ROLE_JOINT urj 
		ON u.ID = urj.USER_ID
	LEFT JOIN ROLE r
		ON urj.ID = r.ID
	LEFT JOIN ROLE_RIGHT_JOINT rrj
		ON r.ID = rrj.ROLE_ID
	LEFT JOIN RIGHT_ ri
		ON rrj.ID = ri.ID
ORDER BY u.ID;