/*
 * myElexis-Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.myelexis.server.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import ch.myelexis.server.model.LockInfo;
import ch.myelexis.server.model.Status;
import ch.myelexis.server.model.Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ch.myelexis.server.client.ApiClient;
/**
 * LockResponse
 */
@JsonPropertyOrder({
  LockResponse.JSON_PROPERTY_STATUS,
  LockResponse.JSON_PROPERTY_LOCK_INFO,
  LockResponse.JSON_PROPERTY_LOCK_REQUEST_TYPE,
  LockResponse.JSON_PROPERTY_OK
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-06T12:40:32.737785+02:00[Europe/Vienna]", comments = "Generator version: 7.16.0")
public class LockResponse {
  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private Status status;

  public static final String JSON_PROPERTY_LOCK_INFO = "lockInfo";
  @jakarta.annotation.Nullable
  private LockInfo lockInfo;

  public static final String JSON_PROPERTY_LOCK_REQUEST_TYPE = "lockRequestType";
  @jakarta.annotation.Nullable
  private Type lockRequestType;

  public static final String JSON_PROPERTY_OK = "ok";
  @jakarta.annotation.Nullable
  private Boolean ok;

  public LockResponse() { 
  }

  public LockResponse status(@jakarta.annotation.Nullable Status status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Status getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable Status status) {
    this.status = status;
  }


  public LockResponse lockInfo(@jakarta.annotation.Nullable LockInfo lockInfo) {
    this.lockInfo = lockInfo;
    return this;
  }

  /**
   * Get lockInfo
   * @return lockInfo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCK_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LockInfo getLockInfo() {
    return lockInfo;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCK_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockInfo(@jakarta.annotation.Nullable LockInfo lockInfo) {
    this.lockInfo = lockInfo;
  }


  public LockResponse lockRequestType(@jakarta.annotation.Nullable Type lockRequestType) {
    this.lockRequestType = lockRequestType;
    return this;
  }

  /**
   * Get lockRequestType
   * @return lockRequestType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCK_REQUEST_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Type getLockRequestType() {
    return lockRequestType;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCK_REQUEST_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockRequestType(@jakarta.annotation.Nullable Type lockRequestType) {
    this.lockRequestType = lockRequestType;
  }


  public LockResponse ok(@jakarta.annotation.Nullable Boolean ok) {
    this.ok = ok;
    return this;
  }

  /**
   * Get ok
   * @return ok
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getOk() {
    return ok;
  }


  @JsonProperty(value = JSON_PROPERTY_OK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOk(@jakarta.annotation.Nullable Boolean ok) {
    this.ok = ok;
  }


  /**
   * Return true if this LockResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LockResponse lockResponse = (LockResponse) o;
    return Objects.equals(this.status, lockResponse.status) &&
        Objects.equals(this.lockInfo, lockResponse.lockInfo) &&
        Objects.equals(this.lockRequestType, lockResponse.lockRequestType) &&
        Objects.equals(this.ok, lockResponse.ok);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, lockInfo, lockRequestType, ok);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LockResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lockInfo: ").append(toIndentedString(lockInfo)).append("\n");
    sb.append("    lockRequestType: ").append(toIndentedString(lockRequestType)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `lockInfo` to the URL query string
    if (getLockInfo() != null) {
      joiner.add(getLockInfo().toUrlQueryString(prefix + "lockInfo" + suffix));
    }

    // add `lockRequestType` to the URL query string
    if (getLockRequestType() != null) {
      joiner.add(String.format(Locale.ROOT, "%slockRequestType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLockRequestType()))));
    }

    // add `ok` to the URL query string
    if (getOk() != null) {
      joiner.add(String.format(Locale.ROOT, "%sok%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOk()))));
    }

    return joiner.toString();
  }
}

