DELETE e1 FROM BEHDL_DG_JOINT e1, BEHDL_DG_JOINT e2 
WHERE e1.DiagnoseID = e2.DiagnoseID 
AND e1.BehandlungsID = e2.BehandlungsID 
AND e1.id > e2.id;

ALTER TABLE BEHDL_DG_JOINT
CHANGE COLUMN ID ID VARCHAR(25) NULL,
CHANGE COLUMN BehandlungsID BehandlungsID VARCHAR(25) NOT NULL,
CHANGE COLUMN DiagnoseID DiagnoseID VARCHAR(25) NOT NULL,
DROP PRIMARY KEY,
ADD PRIMARY KEY (BehandlungsID, DiagnoseID);