ALTER TABLE USERCONFIG DROP CONSTRAINT if exists userconfig_pkey;
-- Technically, a primary key constraint is simply a combination of a unique constraint and a not-null constraint.
DELETE FROM USERCONFIG WHERE USERID IS NULL;
DELETE FROM USERCONFIG WHERE PARAM IS NULL;
ALTER TABLE USERCONFIG ALTER COLUMN USERID SET NOT NULL;
ALTER TABLE USERCONFIG ALTER COLUMN PARAM SET NOT NULL;
DELETE FROM USERCONFIG
WHERE CTID IN (
     SELECT MIN(CTID) FROM USERCONFIG
     GROUP BY USERID, PARAM
     HAVING COUNT(*) > 1
);
ALTER TABLE USERCONFIG ADD PRIMARY KEY (USERID , PARAM);

UPDATE VK_PREISE SET ID = substr(md5(random()::text), 1, 25) WHERE ID is NULL;
ALTER TABLE VK_PREISE DROP CONSTRAINT IF EXISTS VK_PREISE_PKEY;
ALTER TABLE VK_PREISE ALTER ID SET NOT NULL;
ALTER TABLE VK_PREISE ADD PRIMARY KEY (ID);
