DELETE FROM REMINDERS_RESPONSIBLE_LINK WHERE ID IN  (SELECT  e1.ID FROM REMINDERS_RESPONSIBLE_LINK AS e1
JOIN REMINDERS_RESPONSIBLE_LINK AS e2 
ON e1.REMINDERID = e2.REMINDERID AND e1.RESPONSIBLEID = e2.RESPONSIBLEID AND e1.id > e2.id);

ALTER TABLE REMINDERS_RESPONSIBLE_LINK DROP PRIMARY KEY;
ALTER TABLE REMINDERS_RESPONSIBLE_LINK ALTER COLUMN ID VARCHAR(25) NULL;
ALTER TABLE REMINDERS_RESPONSIBLE_LINK ALTER COLUMN RESPONSIBLEID VARCHAR(25) NOT NULL;
ALTER TABLE REMINDERS_RESPONSIBLE_LINK ALTER COLUMN REMINDERID VARCHAR(25) NOT NULL;
ALTER TABLE REMINDERS_RESPONSIBLE_LINK ADD PRIMARY KEY ( RESPONSIBLEID , REMINDERID );

ALTER TABLE REMINDERS ADD ExtInfo BLOB;