ALTER TABLE USER_ DROP INDEX APIKEY_UNIQUE;
ALTER TABLE USER_ CHANGE COLUMN APIKEY TOTP CHAR(16) NULL DEFAULT NULL;
ALTER TABLE USER_ ADD ALLOW_EXTERNAL CHAR(1) NOT NULL DEFAULT '0';

INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('esadmin', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('fhir', '1');