<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://ch.elexis.core/model/model" nsPrefix="ch.elexis.core.model">
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true" interface="true">
    <eOperations name="getId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return an identifier for this object that is guaranteed to be globally unique."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="return a human readable identifier (not necessarily unique) for this Object"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="addXid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="domain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="updateIfExists" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="getXid" eType="#//IXid">
      <eParameters name="domain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getChanged">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="#//Identifiable"/>
      </eGenericType>
    </eOperations>
    <eOperations name="addChanged">
      <eParameters name="changed" eType="#//Identifiable"/>
    </eOperations>
    <eOperations name="clearChanged"/>
    <eOperations name="getRefresh">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="#//Identifiable"/>
      </eGenericType>
    </eOperations>
    <eOperations name="addRefresh">
      <eParameters name="changed" eType="#//Identifiable"/>
    </eOperations>
    <eOperations name="clearRefresh"/>
    <eOperations name="addUpdated">
      <eParameters name="feature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    </eOperations>
    <eOperations name="getUpdated">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eGenericType>
    </eOperations>
    <eOperations name="clearUpdated"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastupdate" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deleteable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IXid" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable">
    <eOperations name="getObject">
      <eGenericType eTypeParameter="#//IXid/getObject/T"/>
      <eTypeParameters name="T"/>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//IXid/getObject/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="setObject">
      <eParameters name="object" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quality" eType="ecore:EDataType types.ecore#//XidQuality"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IContact" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithExtInfo">
    <eOperations name="asIPerson" eType="#//IPerson">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Re-loads the given IContact as IPerson, iff it isPerson(). Returns &lt;code>null&lt;/code> if not person or could not load."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="asIPatient" eType="#//IPatient">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Re-loads the given IContact as IPatient, iff it isPatient(). Returns &lt;code>null&lt;/code> if not patient or could not load."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="asIOrganization" eType="#//IOrganization">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Re-loads the given IContact as IOrganization, iff it isOrganization(). Returns &lt;code>null&lt;/code> if not organization or could not load."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="person" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="organization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="organisation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="laboratory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType types.ecore#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="website" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mobile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="address" upperBound="-1"
        eType="#//IAddress"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postalAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//IImage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedContacts" upperBound="-1"
        eType="#//IRelatedContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deceased" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPerson" abstract="true" interface="true"
      eSuperTypes="#//IContact">
    <eOperations name="getAgeInYears" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getAgeAtIn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eParameters name="reference" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
      <eParameters name="chronoUnit" eType="ecore:EDataType types.ecore#//ChronoUnit"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfBirth" eType="ecore:EDataType types.ecore#//LocalDateTime">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="dob"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" eType="ecore:EDataType types.ecore#//Gender"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titelSuffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="description2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="description1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maritalStatus" eType="ecore:EDataType types.ecore#//MaritalStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legalGuardian" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfDeath" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOrganization" abstract="true" interface="true"
      eSuperTypes="#//IContact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insuranceXmlName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insuranceLawCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILaboratory" abstract="true" interface="true"
      eSuperTypes="#//IOrganization"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPatient" abstract="true" interface="true"
      eSuperTypes="#//IPerson">
    <eOperations name="getPatientNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="setPatientNr">
      <eParameters name="patientNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getMedication">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="#//IPrescription"/>
      </eGenericType>
      <eParameters name="filterType" upperBound="-1" eType="ecore:EDataType types.ecore#//EntryType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="familyDoctor" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagnosen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="risk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="familyAnamnese" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personalAnamnese" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allergies" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverages" upperBound="-1"
        eType="#//ICoverage" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMandator" abstract="true" interface="true"
      eSuperTypes="#//IContact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biller" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Whether this IMandator is allowed to bill"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IUser" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable">
    <eOperations name="addRole" eType="#//IRole">
      <eParameters name="role" lowerBound="1" eType="#//IRole"/>
    </eOperations>
    <eOperations name="removeRole">
      <eParameters name="role" lowerBound="1" eType="#//IRole"/>
    </eOperations>
    <eOperations name="login" eType="#//IUser">
      <eParameters name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="password" eType="ecore:EDataType types.ecore#//charArray"/>
    </eOperations>
    <eOperations name="isInternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="setRoles">
      <eParameters name="roles">
        <eGenericType eClassifier="ecore:EClass types.ecore#//List">
          <eTypeArguments eClassifier="#//IRole"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hashedPassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="salt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedContact" eType="#//IContact">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="kontakt"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//IRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowExternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="administrator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associatedContactId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleIds" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IUserGroup" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable #//WithExtInfo">
    <eOperations name="addRole" eType="#//IRole">
      <eParameters name="role" lowerBound="1" eType="#//IRole"/>
    </eOperations>
    <eOperations name="removeRole">
      <eParameters name="role" lowerBound="1" eType="#//IRole"/>
    </eOperations>
    <eOperations name="addUser" eType="#//IUser">
      <eParameters name="user" lowerBound="1" eType="#//IUser"/>
    </eOperations>
    <eOperations name="removeUser">
      <eParameters name="user" lowerBound="1" eType="#//IUser"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//IUser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//IRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILabItem" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="getVariableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the variable name of this LabItem as used in LabItems of type formula for cross-reference"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isNoReferenceValueItem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typ" eType="ecore:EDataType types.ecore#//LabItemTyp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceMale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceFemale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loincCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="billingCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//ILabMapping" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILabResult" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable #//WithExtInfo">
    <eOperations name="getLabOrder" eType="#//ILabOrder">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Load the associated LabOrder entry. Returns null if not found or LabOrder marked as deleted."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getLabOrder" eType="#//ILabOrder">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Value&#x9;Load the associated LabOrder entry. Returns null if not found."/>
      </eAnnotations>
      <eParameters name="includeDeleted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Load the Laborder even if marked as deleted"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceMale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceFemale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observationTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="analyseTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transmissionTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathologic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathologicDescription"
        eType="ecore:EDataType types.ecore#//PathologicDescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="#//ILabItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//IPatient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILabOrder" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//ILabResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="#//ILabItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//IPatient"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeStamp" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observationTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType types.ecore#//LabOrderState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userResolved" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILabMapping" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="#//ILabItem">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="labitem"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDocument" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="getContent" eType="ecore:EDataType types.ecore#//InputStream"/>
    <eOperations name="setContent">
      <eParameters name="content" eType="ecore:EDataType types.ecore#//InputStream"/>
    </eOperations>
    <eOperations name="setStatus">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Convenience method: Activate or deactive the given status for the document."/>
      </eAnnotations>
      <eParameters name="status" lowerBound="1" eType="ecore:EEnum types.ecore#//DocumentStatus"/>
      <eParameters name="active" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="getContentLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return the size of the content without fetching it, returns -1 if it could not be determined"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        upperBound="-1" eType="ecore:EEnum types.ecore#//DocumentStatus">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="One or multiple states this document may have. The states represented are bitwise appliable."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastchanged" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" lowerBound="1"
        eType="#//ICategory">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="Brief#attributeName" value="typ"/>
        <details key="DocHandle#attributeName" value="category"/>
        <details key="BriefVorlage#attributeName" value="typ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="history" upperBound="-1"
        eType="#//IHistory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keywords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//IPatient">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="DocHandle#attributeName" value="kontakt"/>
        <details key="Brief#attributeName" value="patient"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//IContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IHistory" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EEnum types.ecore#//DocumentStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICategory" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDocumentLetter" abstract="true" interface="true"
      eSuperTypes="#//IDocument">
    <eOperations name="isTemplate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encounter" eType="#//IEncounter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipient" eType="#//IContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDocumentTemplate" abstract="true" interface="true"
      eSuperTypes="#//IDocument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateTyp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="askForAddressee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ISticker" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A sticker is a piece of information that may be attached to an Identifiable. It can either exist for itself, or as an attachedTo (bound to an identifiable) instance."/>
    </eAnnotations>
    <eOperations name="getLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="background" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foreground" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//IImage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachedTo" eType="#//Identifiable"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If not null this is an attached instance of a sticker. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attachedToData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="optionally attached data on an attached sticker instance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="ecore:EClass types.ecore#//Comparable">
      <eTypeArguments eClassifier="#//ISticker"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//Deleteable"/>
    <eGenericSuperTypes eClassifier="#//Identifiable"/>
    <eGenericSuperTypes eClassifier="#//WithAssignableId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICodeElement" abstract="true" interface="true">
    <eOperations name="getCodeSystemName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getCodeSystemCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICodeElementBlock" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//ICodeElement">
    <eOperations name="getDiffToReferences">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="#//ICodeElement"/>
      </eGenericType>
      <eParameters name="elements">
        <eGenericType eClassifier="ecore:EClass types.ecore#//List">
          <eTypeArguments eClassifier="#//ICodeElement"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="addElement">
      <eParameters name="element" eType="#//ICodeElement"/>
    </eOperations>
    <eOperations name="removeElement">
      <eParameters name="element" eType="#//ICodeElement"/>
    </eOperations>
    <eOperations name="moveElement">
      <eParameters name="element" eType="#//ICodeElement"/>
      <eParameters name="up" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="getElements">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="#//ICodeElement"/>
      </eGenericType>
      <eParameters name="encounter" eType="#//IEncounter"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ICodeElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementReferences" upperBound="-1"
        eType="#//ICodeElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="macro" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBillable" abstract="true" interface="true"
      eSuperTypes="#//ICodeElement #//Identifiable">
    <eOperations name="getVatInfo" eType="ecore:EDataType types.ecore#//VatInfo"/>
    <eOperations name="getOptifier" eType="#//IBillableOptifier"/>
    <eOperations name="getVerifier" eType="#//IBillableVerifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBillableVerifier" abstract="true" interface="true">
    <eOperations name="verifyAdd">
      <eGenericType eClassifier="ecore:EClass types.ecore#//Result">
        <eTypeArguments eClassifier="#//IBillable"/>
      </eGenericType>
      <eParameters name="billable" eType="#//IBillable"/>
      <eParameters name="encounter" eType="#//IEncounter"/>
      <eParameters name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="verify">
      <eGenericType eClassifier="ecore:EClass types.ecore#//Result">
        <eTypeArguments eClassifier="#//IBilled"/>
      </eGenericType>
      <eParameters name="encounter" eType="#//IEncounter"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBillableOptifier" abstract="true" interface="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//IBillable"/>
    </eTypeParameters>
    <eOperations name="add">
      <eGenericType eClassifier="ecore:EClass types.ecore#//Result">
        <eTypeArguments eClassifier="#//IBilled"/>
      </eGenericType>
      <eParameters name="billable">
        <eGenericType eTypeParameter="#//IBillableOptifier/T"/>
      </eParameters>
      <eParameters name="encounter" eType="#//IEncounter"/>
      <eParameters name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="save" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="putContext">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="clearContext"/>
    <eOperations name="remove">
      <eGenericType eClassifier="ecore:EClass types.ecore#//Result">
        <eTypeArguments eClassifier="#//IBilled"/>
      </eGenericType>
      <eParameters name="billed" eType="#//IBilled"/>
      <eParameters name="encounter" eType="#//IEncounter"/>
    </eOperations>
    <eOperations name="getFactor">
      <eGenericType eClassifier="ecore:EDataType types.ecore#//Optional">
        <eTypeArguments eClassifier="#//IBillingSystemFactor"/>
      </eGenericType>
      <eParameters name="encounter" eType="#//IEncounter"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IService" abstract="true" interface="true"
      eSuperTypes="#//IBillable #//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="netPrice" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICustomService" abstract="true" interface="true"
      eSuperTypes="#//IService">
    <eOperations name="setCodeSystemCode">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IArticle" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//IBillable #//Deleteable #//WithExtInfo">
    <eOperations name="isProduct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getPackages">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="#//IArticle"/>
      </eGenericType>
    </eOperations>
    <eOperations name="setCode">
      <eParameters name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="isVaccination" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gtin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="ean"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atcCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sellingSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" eType="#//IArticle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purchasePrice" eType="ecore:EDataType types.ecore#//Money">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="ekPreis"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sellingPrice" eType="ecore:EDataType types.ecore#//Money">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="vkPreis"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obligation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typ" eType="ecore:EDataType types.ecore#//ArticleTyp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subTyp" eType="ecore:EDataType types.ecore#//ArticleSubTyp">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="codeclass"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageSizeString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IArticleDefaultSignature" abstract="true"
      interface="true" eSuperTypes="#//Deleteable #//Identifiable #//WithExtInfo">
    <eOperations name="setArticle">
      <eParameters name="article" eType="#//IArticle"/>
    </eOperations>
    <eOperations name="isAtc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getSignatureAsDosisString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atcCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="morning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evening" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="night" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freeText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="medicationType" eType="ecore:EDataType types.ecore#//EntryType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disposalType" eType="ecore:EDataType types.ecore#//EntryType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType types.ecore#//LocalDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDiagnosis" abstract="true" interface="true"
      eSuperTypes="#//ICodeElement #//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFreeTextDiagnosis" abstract="true"
      interface="true" eSuperTypes="#//IDiagnosis"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDiagnosisReference" abstract="true"
      interface="true" eSuperTypes="#//IDiagnosis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referredClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDiagnosisTree" abstract="true" interface="true"
      eSuperTypes="#//IDiagnosis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//IDiagnosisTree"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//IDiagnosisTree"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICustomDiagnosis" abstract="true" interface="true"
      eSuperTypes="#//IDiagnosisTree"/>
  <eClassifiers xsi:type="ecore:EClass" name="ICoverage" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable #//WithExtInfo">
    <eOperations name="isOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" lowerBound="1"
        eType="#//IPatient">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="patientKontakt"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFrom" lowerBound="1"
        eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datumvon"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="costBearer" eType="#//IContact">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="kostentrkontakt"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The &quot;Kostenträger&quot;, &quot;Payor&quot;. If Tiers Garant (TG) costBearer and guarantor differ.\n(Validiert JK 3.7.23)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insuranceNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="versnummer"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTo" eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datumbis"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="billingProposalDate" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encounters" upperBound="-1"
        eType="#//IEncounter" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billingSystem" lowerBound="1"
        eType="#//IBillingSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guarantor" eType="#//IContact">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The &quot;Rechnungsempfänger&quot;, &quot;Garant&quot;. If Tiers Payant (TP) identical to the costBearer. TP is only valid, if both costBearer and gurarantor are Organizations. If Tiers Garant (TG) differs from the costBearer. Bedeutung Begriff TP: Ein Dritter (Tiers, die Versicherung) bezahlt direkt für die Kosten (payer: bezahlen).\n(Validiert JK 3.7.23)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBillingSystemFactor" abstract="true"
      interface="true" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="system" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="typ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datum_von"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datum_bis"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IConfig" abstract="true" interface="true"
      eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="param"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IUserConfig" abstract="true" interface="true"
      eSuperTypes="#//IConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//IContact">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="ownerId"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPeriod" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="isAllDay" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Is all day if the startTime is at the start of day (i.e. 00:00:00.000000000) and an endTime is null"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WithExtInfo" abstract="true" interface="true">
    <eOperations name="getExtInfo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="setExtInfo">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getMap">
      <eGenericType eClassifier="ecore:EClass types.ecore#//Map">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IRole" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//WithAssignableId #//WithExtInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedRights" upperBound="-1"
        eType="#//IRight" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBlob" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithAssignableId">
    <eOperations name="getStringContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="setStringContent">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getMapContent">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
    </eOperations>
    <eOperations name="setMapContent">
      <eParameters name="map">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datum"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEncounter" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="addDiagnosis">
      <eParameters name="diagnosis" lowerBound="1" eType="#//IDiagnosis"/>
    </eOperations>
    <eOperations name="removeDiagnosis">
      <eParameters name="diagnosis" lowerBound="1" eType="#//IDiagnosis"/>
    </eOperations>
    <eOperations name="removeBilled">
      <eParameters name="billed" lowerBound="1" eType="#//IBilled"/>
    </eOperations>
    <eOperations name="getInvoiceState" eType="ecore:EDataType types.ecore#//InvoiceState"/>
    <eOperations name="getHeadVersionInPlaintext" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the head version of the consultation text in plaintext (masking possible SamDas XML formatting). Returns empty string if none found."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeStamp" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datum"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="billable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//IPatient"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="mandant"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billed" upperBound="-1"
        eType="#//IBilled"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnoses" upperBound="-1"
        eType="#//IDiagnosisReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" eType="#//ICoverage">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="fall"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionedEntry" eType="ecore:EDataType types.ecore#//VersionedResource">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="eintrag"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice" eType="#//IInvoice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBilled" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithExtInfo">
    <eOperations name="isChangedPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isNonIntegerAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getPrimaryScaleFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getSecondaryScaleFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="copy">
      <eParameters name="to" eType="#//IBilled"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billable" eType="#//IBillable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encounter" eType="#//IEncounter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scaledPrice" eType="ecore:EDataType types.ecore#//Money"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="netPrice" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondaryScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="total" eType="ecore:EDataType types.ecore#//Money"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biller" eType="#//IContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IInvoiceBilled" abstract="true" interface="true"
      eSuperTypes="#//IBilled">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice" eType="#//IInvoice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IInvoice" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithExtInfo">
    <eOperations name="addTrace">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getTrace">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="adjustAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value" eType="ecore:EDataType types.ecore#//Money"/>
    </eOperations>
    <eOperations name="reject">
      <eParameters name="rejectCode" eType="ecore:EDataType types.ecore#//InvoiceRejectCode"/>
      <eParameters name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addAttachment">
      <eParameters name="attachment" lowerBound="1" eType="#//IDocument"/>
    </eOperations>
    <eOperations name="removeAttachment">
      <eParameters name="attachment" lowerBound="1" eType="#//IDocument"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType types.ecore#//InvoiceState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" eType="#//ICoverage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encounters" upperBound="-1"
        eType="#//IEncounter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billed" upperBound="-1"
        eType="#//IBilled"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFrom" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTo" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalAmount" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openAmount" eType="ecore:EDataType types.ecore#//Money"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="payedAmount" eType="ecore:EDataType types.ecore#//Money"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="demandAmount" eType="ecore:EDataType types.ecore#//Money"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateDate" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payments" upperBound="-1"
        eType="#//IPayment" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactions" upperBound="-1"
        eType="#//IAccountTransaction" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachments" upperBound="-1"
        eType="#//IDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IStock" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithAssignableId">
    <eOperations name="isCommissioningSystem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A unique code to define a specific stock"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driverUuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driverConfig" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//IPerson">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The person the contents of this stock (ultimately) belong to."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The location of this stock. A room name or other address. If the value is &quot;Patient&quot; then it is a &quot;virtual stock&quot; that manages patient orders."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible" eType="#//IContact">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The person or contact responsible for managing this stock"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stockEntries" upperBound="-1"
        eType="#//IStockEntry" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IStockEntry" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumStock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentStock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumStock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fractionUnits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stock" eType="#//IStock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="article" eType="#//IArticle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//IContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOrderEntry" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="order" eType="#//IOrder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stock" eType="#//IStock"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="article" eType="#//IArticle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType types.ecore#//OrderEntryState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delivered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOutputLog" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithExtInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creatorId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputterStatus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOrder" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="addEntry" eType="#//IOrderEntry">
      <eParameters name="article" eType="#//IArticle"/>
      <eParameters name="stock" eType="#//IStock"/>
      <eParameters name="provider" eType="#//IContact"/>
      <eParameters name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="isDone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="findOrderEntry" eType="#//IOrderEntry">
      <eParameters name="stock" eType="#//IStock"/>
      <eParameters name="article" eType="#//IArticle"/>
    </eOperations>
    <eOperations name="isPartialDone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//IOrderEntry"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAddress" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType types.ecore#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writtenAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EEnum types.ecore#//AddressType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact" lowerBound="1"
        eType="#//IContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IImage" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithAssignableId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType" eType="ecore:EDataType types.ecore#//MimeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WithAssignableId" abstract="true" interface="true">
    <eOperations name="setId">
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPrescription" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithExtInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" lowerBound="1"
        eType="#//IPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="article" eType="#//IArticle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFrom" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTo" eType="ecore:EDataType types.ecore#//LocalDateTime">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="dateUntil"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dosageInstruction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disposalComment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entryType" eType="ecore:EDataType types.ecore#//EntryType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applied" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortOrder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prescriptor" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipe" eType="#//IRecipe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billed" eType="#//IBilled"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IRight" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithAssignableId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localizedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//IRight"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBillingSystem" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="law" eType="ecore:EDataType types.ecore#//BillingLaw"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IRecipe" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="removePrescription">
      <eParameters name="prescription" lowerBound="1" eType="#//IPrescription"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" lowerBound="1"
        eType="#//IPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prescriptions" upperBound="-1"
        eType="#//IPrescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" eType="#//IDocumentLetter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBlobSecondary" abstract="true" interface="true"
      eSuperTypes="#//IBlob"/>
  <eClassifiers xsi:type="ecore:EClass" name="IRelatedContact" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="myContact" lowerBound="1"
        eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherContact" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipDescription"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="myType" eType="ecore:EEnum types.ecore#//RelationshipType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherType" eType="ecore:EEnum types.ecore#//RelationshipType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPayment" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice" eType="#//IInvoice"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAccountTransaction" abstract="true"
      interface="true" eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice" eType="#//IInvoice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payment" eType="#//IPayment">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="zahlung"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//IPatient"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="account" eType="#//IAccount"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAccount" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMessage" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="setSender">
      <eParameters name="user" eType="#//IUser"/>
    </eOperations>
    <eOperations name="addMessageCode">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addReceiver">
      <eParameters name="receiver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addReceiver">
      <eParameters name="receiver" eType="#//IUser"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sender" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The sender of the message. Possibly a userid that may be resolved to an IUser or another identifier (e.g. a station or system name)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiver" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The list of receivers. If empty, send message to everybody."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="senderAcceptsAnswer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="wether the sender of this message will accept or handle an answer, i.e. unidirectional communication."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createDateTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the message text to be read by the receiving user(s)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageCodes" transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="a message code to allow for extended representation and/or action configuration (e.g. show a specific image, perform a specific task)"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messagePriority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preferredTransporters"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="By default the MessageService tries to send over all transporters (ordered by priority descending) until one successfully sends it.&#xA;Providing transporter ids here overrides the transporter selection and their order."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITextTemplate" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithExtInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EEnum types.ecore#//TextTemplateCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="template" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAppointment" abstract="true" interface="true"
      eSuperTypes="#//IPeriod">
    <eOperations name="getContact" eType="#//IContact"/>
    <eOperations name="getStateHistoryFormatted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="formatPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="grund"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="termintyp"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationMinutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="dauer"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schedule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="bereich"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subjectOrPatient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="patid"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="treatmentReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Enumerated reason why this appointment was created. Currently used by RH connector"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caseType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Enumerated case type of this appointment. Currently used by RH connector"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insuranceType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Enumerated insurance type of this appointment. Currently used by RH connector"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkgroup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="angelegt"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastEdit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="lastedit"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateHistory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="statusHistory"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recurring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdBy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="erstelltvon"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locked" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAppointmentSeries" abstract="true"
      interface="true" eSuperTypes="#//IAppointment">
    <eOperations name="getAsSeriesExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getAppointments">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="#//IAppointment"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seriesType" eType="ecore:EDataType types.ecore#//SeriesType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endingType" eType="ecore:EDataType types.ecore#//EndingType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seriesStartDate" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seriesStartTime" eType="ecore:EDataType types.ecore#//LocalTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seriesEndDate" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seriesEndTime" eType="ecore:EDataType types.ecore#//LocalTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seriesPatternString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endingPatternString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootAppointment" eType="#//IAppointment"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ISickCertificate" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//IPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" eType="#//ICoverage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="letter" eType="#//IDocumentLetter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDayMessage" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable #//WithAssignableId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IReminder" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable #//WithExtInfo">
    <eOperations name="addResponsible">
      <eParameters name="responsible" lowerBound="1" eType="#//IContact"/>
    </eOperations>
    <eOperations name="removeResponsible">
      <eParameters name="responsible" lowerBound="1" eType="#//IContact"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creator" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible" upperBound="-1"
        eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact" eType="#//IContact">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="kontakt"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="due" eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="dateDue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType types.ecore#//ProcessStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EDataType types.ecore#//Visibility"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType types.ecore#//Priority"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType types.ecore#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responsibleAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//IUserGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IReminderResponsibleLink" abstract="true"
      interface="true" eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reminder" eType="#//IReminder"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible" eType="#//IContact"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IVaccination" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithExtInfo">
    <eOperations name="getPerformerLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="setPerformerLabel">
      <eParameters name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" lowerBound="1"
        eType="#//IPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="article" eType="#//IArticle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="articleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="articleGtin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="articleAtc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lotNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfAdministration" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ingredientsAtc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performer" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="side" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
