<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://ch.elexis.core/model/model" nsPrefix="ch.elexis.core.model">
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true" interface="true">
    <eOperations name="getId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return an identifier for this object that is guaranteed to be globally unique."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="return a human readable identifier (not necessarily unique) for this Object"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="addXid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="domain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="updateIfExists" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="getXid" eType="#//IXid">
      <eParameters name="domain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getLastupdate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deleteable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IXid" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable">
    <eOperations name="getObject">
      <eGenericType eTypeParameter="#//IXid/getObject/T"/>
      <eTypeParameters name="T"/>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//IXid/getObject/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="setObject">
      <eParameters name="object" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quality" eType="ecore:EDataType types.ecore#//XidQuality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="object"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IContact" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithExtInfo">
    <eOperations name="addAddress" eType="#//IAddress">
      <eParameters name="address" eType="#//IAddress"/>
    </eOperations>
    <eOperations name="addRelatedContact" eType="#//IRelatedContact">
      <eParameters name="relatedContact" eType="#//IRelatedContact"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="person" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="organization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="laboratory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType types.ecore#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="website" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mobile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="address" upperBound="-1"
        eType="#//IAddress"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postalAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//IImage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedContacts" upperBound="-1"
        eType="#//IRelatedContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPerson" abstract="true" interface="true"
      eSuperTypes="#//IContact">
    <eOperations name="getAgeInYears" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getAgeAtIn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eParameters name="reference" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
      <eParameters name="chronoUnit" eType="ecore:EDataType types.ecore#//ChronoUnit"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfBirth" eType="ecore:EDataType types.ecore#//LocalDateTime">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="dob"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" eType="ecore:EDataType types.ecore#//Gender"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titelSuffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="description2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="description1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maritalStatus" eType="ecore:EDataType types.ecore#//MaritalStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legalGuardian" eType="#//IPerson"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOrganization" abstract="true" interface="true"
      eSuperTypes="#//IContact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insuranceXmlName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insuranceLawCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILaboratory" abstract="true" interface="true"
      eSuperTypes="#//IOrganization"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPatient" abstract="true" interface="true"
      eSuperTypes="#//IPerson">
    <eOperations name="getPatientNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="setPatientNr">
      <eParameters name="patientNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addCoverage" eType="#//ICoverage">
      <eParameters name="coverage" lowerBound="1" eType="#//ICoverage"/>
    </eOperations>
    <eOperations name="getMedication">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="#//IPrescription"/>
      </eGenericType>
      <eParameters name="filterType" upperBound="-1" eType="ecore:EDataType types.ecore#//EntryType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="familyDoctor" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagnosen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="risk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="familyAnamnese" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personalAnamnese" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allergies" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverages" upperBound="-1"
        eType="#//ICoverage" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMandator" abstract="true" interface="true"
      eSuperTypes="#//IContact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biller" eType="#//IContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IUser" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable">
    <eOperations name="addRole" eType="#//IRole">
      <eParameters name="role" lowerBound="1" eType="#//IRole"/>
    </eOperations>
    <eOperations name="removeRole">
      <eParameters name="role" lowerBound="1" eType="#//IRole"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hashedPassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="salt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedContact" eType="#//IContact">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="kontakt"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//IRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowExternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="administrator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILabItem" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="addMapping" eType="#//ILabMapping">
      <eParameters name="mapping" lowerBound="1" eType="#//ILabMapping"/>
    </eOperations>
    <eOperations name="removeMapping" lowerBound="1">
      <eParameters name="mapping" eType="#//ILabMapping"/>
    </eOperations>
    <eOperations name="getVariableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the variable name of this LabItem as used in LabItems of type formula for cross-reference"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typ" eType="ecore:EDataType types.ecore#//LabItemTyp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceMale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceFemale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loincCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="billingCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//ILabMapping" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILabResult" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable #//WithExtInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceMale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceFemale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observationTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="analyseTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transmissionTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathologic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathologicDescription"
        eType="ecore:EDataType types.ecore#//PathologicDescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="#//ILabItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//IPatient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILabOrder" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//ILabResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="#//ILabItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//IPatient"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeStamp" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observationTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType types.ecore#//LabOrderState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILabMapping" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="#//ILabItem">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="labitem"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDocument" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="getContent" eType="ecore:EDataType types.ecore#//InputStream"/>
    <eOperations name="setContent">
      <eParameters name="content" eType="ecore:EDataType types.ecore#//InputStream"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EEnum types.ecore#//DocumentStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastchanged" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" lowerBound="1"
        eType="#//ICategory">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="Brief#attributeName" value="typ"/>
        <details key="DocHandle#attributeName" value="category"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="history" upperBound="-1"
        eType="#//IHistory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keywords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//IPatient">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="DocHandle#attributeName" value="kontakt"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//IContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IHistory" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EEnum types.ecore#//DocumentStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICategory" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDocumentLetter" abstract="true" interface="true"
      eSuperTypes="#//IDocument"/>
  <eClassifiers xsi:type="ecore:EClass" name="ISticker" abstract="true" interface="true">
    <eOperations name="getLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="background" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foreground" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//IImage"/>
    <eGenericSuperTypes eClassifier="ecore:EClass types.ecore#//Comparable">
      <eTypeArguments eClassifier="#//ISticker"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//Deleteable"/>
    <eGenericSuperTypes eClassifier="#//Identifiable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICodeElement" abstract="true" interface="true">
    <eOperations name="getCodeSystemName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getCodeSystemCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICodeElementBlock" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//ICodeElement">
    <eOperations name="getDiffToReferences">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="#//ICodeElement"/>
      </eGenericType>
      <eParameters name="elements">
        <eGenericType eClassifier="ecore:EClass types.ecore#//List">
          <eTypeArguments eClassifier="#//ICodeElement"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="addElement">
      <eParameters name="element" eType="#//ICodeElement"/>
    </eOperations>
    <eOperations name="removeElement">
      <eParameters name="element" eType="#//ICodeElement"/>
    </eOperations>
    <eOperations name="moveElement">
      <eParameters name="element" eType="#//ICodeElement"/>
      <eParameters name="up" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="getElements">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="#//ICodeElement"/>
      </eGenericType>
      <eParameters name="encounter" eType="#//IEncounter"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ICodeElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementReferences" upperBound="-1"
        eType="#//ICodeElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="macro" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBillable" abstract="true" interface="true"
      eSuperTypes="#//ICodeElement #//Identifiable">
    <eOperations name="getVatInfo" eType="ecore:EDataType types.ecore#//VatInfo"/>
    <eOperations name="getOptifier" eType="#//IBillableOptifier"/>
    <eOperations name="getVerifier" eType="#//IBillableVerifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBillableVerifier" abstract="true" interface="true">
    <eOperations name="verifyAdd">
      <eGenericType eClassifier="ecore:EClass types.ecore#//Result">
        <eTypeArguments eClassifier="#//IBillable"/>
      </eGenericType>
      <eParameters name="billable" eType="#//IBillable"/>
      <eParameters name="encounter" eType="#//IEncounter"/>
      <eParameters name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBillableOptifier" abstract="true" interface="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//IBillable"/>
    </eTypeParameters>
    <eOperations name="add">
      <eGenericType eClassifier="ecore:EClass types.ecore#//Result">
        <eTypeArguments eClassifier="#//IBilled"/>
      </eGenericType>
      <eParameters name="billable">
        <eGenericType eTypeParameter="#//IBillableOptifier/T"/>
      </eParameters>
      <eParameters name="encounter" eType="#//IEncounter"/>
      <eParameters name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="putContext">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="clearContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IService" abstract="true" interface="true"
      eSuperTypes="#//IBillable #//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="netPrice" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICustomService" abstract="true" interface="true"
      eSuperTypes="#//IService"/>
  <eClassifiers xsi:type="ecore:EClass" name="IArticle" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//IBillable #//Deleteable #//WithExtInfo">
    <eOperations name="isProduct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getPackages">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="#//IArticle"/>
      </eGenericType>
    </eOperations>
    <eOperations name="setCode">
      <eParameters name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gtin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="ean"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atcCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sellingSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" eType="#//IArticle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purchasePrice" eType="ecore:EDataType types.ecore#//Money">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="ekPreis"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sellingPrice" eType="ecore:EDataType types.ecore#//Money">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="vkPreis"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obligation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typ" eType="ecore:EDataType types.ecore#//ArticleTyp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subTyp" eType="ecore:EDataType types.ecore#//ArticleSubTyp">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="codeclass"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IArticleDefaultSignature" abstract="true"
      interface="true" eSuperTypes="#//Deleteable #//Identifiable #//WithExtInfo">
    <eOperations name="setArticle">
      <eParameters name="article" eType="#//IArticle"/>
    </eOperations>
    <eOperations name="isAtc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getSignatureAsDosisString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atcCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="morning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evening" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="night" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freeText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="medicationType" eType="ecore:EDataType types.ecore#//EntryType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disposalType" eType="ecore:EDataType types.ecore#//EntryType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType types.ecore#//LocalDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDiagnosis" abstract="true" interface="true"
      eSuperTypes="#//ICodeElement #//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFreeTextDiagnosis" abstract="true"
      interface="true" eSuperTypes="#//IDiagnosis"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDiagnosisReference" abstract="true"
      interface="true" eSuperTypes="#//IDiagnosis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referredClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDiagnosisTree" abstract="true" interface="true"
      eSuperTypes="#//IDiagnosis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//IDiagnosisTree"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//IDiagnosisTree"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICustomDiagnosis" abstract="true" interface="true"
      eSuperTypes="#//IDiagnosisTree"/>
  <eClassifiers xsi:type="ecore:EClass" name="ICoverage" abstract="true" interface="true"
      eSuperTypes="#//Deleteable #//Identifiable #//WithExtInfo">
    <eOperations name="isOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" lowerBound="1"
        eType="#//IPatient">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="patientKontakt"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFrom" lowerBound="1"
        eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datumvon"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="costBearer" eType="#//IContact">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="kostentrkontakt"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insuranceNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="versnummer"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTo" eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datumbis"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="billingProposalDate" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encounters" upperBound="-1"
        eType="#//IEncounter" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billingSystem" lowerBound="1"
        eType="#//IBillingSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guarantor" eType="#//IContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBillingSystemFactor" abstract="true"
      interface="true" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="system" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="typ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datum_von"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datum_bis"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IConfig" abstract="true" interface="true"
      eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="param"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IUserConfig" abstract="true" interface="true"
      eSuperTypes="#//IConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//IContact">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="ownerId"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPeriod" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WithExtInfo" abstract="true" interface="true">
    <eOperations name="getExtInfo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="setExtInfo">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IRole" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//WithAssignableId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedRights" upperBound="-1"
        eType="#//IRight" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBlob" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithAssignableId">
    <eOperations name="getStringContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="setStringContent">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datum"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEncounter" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="addDiagnosis">
      <eParameters name="diagnosis" lowerBound="1" eType="#//IDiagnosis"/>
    </eOperations>
    <eOperations name="removeDiagnosis">
      <eParameters name="diagnosis" lowerBound="1" eType="#//IDiagnosis"/>
    </eOperations>
    <eOperations name="removeBilled">
      <eParameters name="billed" lowerBound="1" eType="#//IBilled"/>
    </eOperations>
    <eOperations name="getInvoiceState" eType="ecore:EDataType types.ecore#//InvoiceState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeStamp" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="datum"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="billable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//IPatient"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="mandant"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billed" upperBound="-1"
        eType="#//IBilled"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnoses" upperBound="-1"
        eType="#//IDiagnosisReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" eType="#//ICoverage">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="fall"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionedEntry" eType="ecore:EDataType types.ecore#//VersionedResource">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="eintrag"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice" eType="#//IInvoice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBilled" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithExtInfo">
    <eOperations name="isChangedPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isNonIntegerAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getPrimaryScaleFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getSecondaryScaleFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="copy">
      <eParameters name="to" eType="#//IInvoiceBilled"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billable" eType="#//IBillable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encounter" eType="#//IEncounter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="netPrice" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondaryScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="total" eType="ecore:EDataType types.ecore#//Money"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biller" eType="#//IContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IInvoiceBilled" abstract="true" interface="true"
      eSuperTypes="#//IBilled">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice" eType="#//IInvoice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IInvoice" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithExtInfo">
    <eOperations name="addTrace">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getTrace">
      <eGenericType eClassifier="ecore:EClass types.ecore#//List">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="adjustAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value" eType="ecore:EDataType types.ecore#//Money"/>
    </eOperations>
    <eOperations name="reject">
      <eParameters name="rejectCode" eType="ecore:EDataType types.ecore#//InvoiceRejectCode"/>
      <eParameters name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType types.ecore#//InvoiceState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" eType="#//ICoverage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encounters" upperBound="-1"
        eType="#//IEncounter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billed" upperBound="-1"
        eType="#//IBilled"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFrom" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTo" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalAmount" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openAmount" eType="ecore:EDataType types.ecore#//Money"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="payedAmount" eType="ecore:EDataType types.ecore#//Money"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="demandAmount" eType="ecore:EDataType types.ecore#//Money"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IStock" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="isCommissioningSystem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driverUuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driverConfig" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//IMandator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IStockEntry" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumStock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentStock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumStock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fractionUnits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stock" eType="#//IStock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="article" eType="#//IArticle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//IContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOrderEntry" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="order" eType="#//IOrder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stock" eType="#//IStock"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="article" eType="#//IArticle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType types.ecore#//OrderEntryState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOrder" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="addEntry" eType="#//IOrderEntry">
      <eParameters name="article" eType="#//IArticle"/>
      <eParameters name="stock" eType="#//IStock"/>
      <eParameters name="provider" eType="#//IContact"/>
      <eParameters name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="removeEntry">
      <eParameters name="entry" eType="#//IOrderEntry"/>
    </eOperations>
    <eOperations name="addEntry">
      <eParameters name="entry" eType="#//IOrderEntry"/>
    </eOperations>
    <eOperations name="isDone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//IOrderEntry"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAddress" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType types.ecore#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writtenAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EEnum types.ecore#//AddressType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact" lowerBound="1"
        eType="#//IContact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAppointment" abstract="true" interface="true"
      eSuperTypes="#//IPeriod">
    <eOperations name="getContact" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="grund"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="termintyp"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationMinutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="dauer"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schedule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="bereich"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdBy" eType="#//IUser">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="erstelltvon"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subjectOrPatient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="patid"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="treatmentReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkgroup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IImage" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithAssignableId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType" eType="ecore:EDataType types.ecore#//MimeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WithAssignableId" abstract="true" interface="true">
    <eOperations name="setId">
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPrescription" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithExtInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" lowerBound="1"
        eType="#//IPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="article" eType="#//IArticle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFrom" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTo" eType="ecore:EDataType types.ecore#//LocalDateTime">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="dateUntil"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dosageInstruction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disposalComment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entryType" eType="ecore:EDataType types.ecore#//EntryType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applied" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortOrder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prescriptor" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipe" eType="#//IRecipe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billed" eType="#//IBilled"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IRight" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable #//WithAssignableId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localizedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//IRight"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBillingSystem" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="law" eType="ecore:EDataType types.ecore#//BillingLaw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IRecipe" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eOperations name="removePrescription">
      <eParameters name="prescription" lowerBound="1" eType="#//IPrescription"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" lowerBound="1"
        eType="#//IPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandator" eType="#//IMandator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prescriptions" upperBound="-1"
        eType="#//IPrescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" eType="#//IDocumentLetter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBlobSecondary" abstract="true" interface="true"
      eSuperTypes="#//IBlob"/>
  <eClassifiers xsi:type="ecore:EClass" name="IRelatedContact" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="myContact" lowerBound="1"
        eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherContact" eType="#//IContact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipDescription"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="myType" eType="ecore:EEnum types.ecore#//RelationshipType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherType" eType="ecore:EEnum types.ecore#//RelationshipType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPayment" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice" eType="#//IInvoice"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAccountTransaction" abstract="true"
      interface="true" eSuperTypes="#//Identifiable #//Deleteable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice" eType="#//IInvoice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payment" eType="#//IPayment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//IPatient"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType types.ecore#//Money"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="account" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType types.ecore#//LocalDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMessage" abstract="true" interface="true"
      eSuperTypes="#//Identifiable #//Deleteable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A message sent between the involved message parties (see IMessageParty)"/>
    </eAnnotations>
    <eOperations name="setSender">
      <eParameters name="user" eType="#//IUser"/>
    </eOperations>
    <eOperations name="addReceiver">
      <eParameters name="addReceiver" eType="#//IUser"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
        eType="#//IMessageParty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
        upperBound="-1" eType="#//IMessageParty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="senderAcceptsAnswer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="wether the sender of this message will accept or handle answer (e.g. a message sent by the system to an IUser will not necessarily be handled)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createDateTime" eType="ecore:EDataType types.ecore#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the message text to be read by the receiving user(s)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="a message code to allow for extended representation and/or action configuration (e.g. show a specific image, perform a specific task)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messagePriority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMessageParty" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A user or station that either sends or receives a message. XOR user or stationId."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//IUser"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
  </eClassifiers>
</ecore:EPackage>
