ALTER TABLE BEHDL_DG_JOINT
CHANGE COLUMN ID ID VARCHAR(25) NULL,
CHANGE COLUMN BehandlungsID BehandlungsID VARCHAR(25) NOT NULL,
CHANGE COLUMN DiagnoseID DiagnoseID VARCHAR(25) NOT NULL,
DROP PRIMARY KEY,
ADD PRIMARY KEY (BehandlungsID, DiagnoseID);