ALTER TABLE USER_ ADD APIKEY VARCHAR(64) NULL;
CREATE UNIQUE INDEX APIKEY_UNIQUE ON USER_ (APIKEY);

ALTER TABLE KONTAKT MODIFY NatelNr VARCHAR(254);
ALTER TABLE KONTAKT MODIFY Telefon1 VARCHAR(254);

ALTER TABLE ARTIKEL MODIFY Name VARCHAR(254);
ALTER TABLE ARTIKEL MODIFY Name_intern VARCHAR(254);

ALTER TABLE AUF MODIFY AUFZusatz VARCHAR(254);