name: pre_commit
on:
  pull_request:
  push:
    branches-ignore: [ '3.6', '3.7', '3.8', '3.9']

jobs:
  build:
    name: Enforce-Eclipse-Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: actions/setup-python@v2
    - run: sudo add-apt-repository ppa:alexlarsson/flatpak
    - run: sudo apt-get update
    - run: sudo apt-get install flatpak
    - run: flatpak --version
    - run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - run: flatpak install --assumeyes --user --noninteractive flathub org.eclipse.Java
    - run: pip install pre-commit
    - run: pre-commit run --hook-stage manual enforce-eclipse-format --all-files
