#!/bin/sh

# Exit on error
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Ask questions
db_input high elexis/db_type || true
db_input high elexis/db_server || true
db_input high elexis/db_names || true
db_input high elexis/db_password || true

# Show interface
db_go || true